server:
  port: 8081
  servlet:
    context-path: /user

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/fledu_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice # user服务的服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.example.user:
      debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS